version: '1.0'

services:

 postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    networks:
      - local-keycloak
    volumes:
      - db:/var/lib/postgresql/data


 keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    depends_on:
      - postgres
    container_name: DigitalMedia
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /digitalMedia-realm.json
      KC_DB: postgres
      KC_DB_PASSWORD: 1234
      KC_DB_USERNAME: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
    ports:
      - 8082:8080
    restart: unless-stopped
    networks:
      - local-keycloak
    command: start-dev

networks:
  local-keycloak:

volumes:
  db: